

const boats = [
  {
    name: 'Bavaria Cruiser 46',
    image: '/images/bavaria46cruiser.jpg',
    length: '14.27 m',
    capacity: 16,
    price: '616 €',
  },
    {
        name: 'Sun Odyssey 410',
        image: '/images/bavaria46cruiser.jpg',
        length: '12.35 m',
        capacity: 10,
        price: '542 €',
    },
    {
        name: 'Lagoon 42',
        image: '/images/bavaria46cruiser.jpg',
        length: '13.10 m',
        capacity: 12,
        price: '750 €',
    },
    {
        name: 'Beneteau Oceanis 38',
        image: '/images/bavaria46cruiser.jpg',
        length: '11.50 m',
        capacity: 8,
        price: '510 €',
    },
    {
        name: 'Dufour 530',
        image: '/images/bavaria46cruiser.jpg',
        length: '16.35 m',
        capacity: 14,
        price: '680 €',
    },
    {
        name: 'Jeanneau Sun Odyssey 349',
        image: '/images/bavaria46cruiser.jpg',
        length: '10.34 m',
        capacity: 8,
        price: '450 €',
    },
    {
        name: 'Catamaran Lagoon 400',
        image: '/images/bavaria46cruiser.jpg',
        length: '11.97 m',
        capacity: 10,
        price: '900 €',
    },
    {
        name: 'Bénéteau First 31.7',
        image: '/images/bavaria46cruiser.jpg',
        length: '9.60 m',
        capacity: 6,
        price: '350 €',
    },
    {
        name: 'Fountaine Pajot Lucia 40',
        image: '/images/bavaria46cruiser.jpg',
        length: '11.73 m',
        capacity: 10,
        price: '850 €',
    },
    {
        name: 'Jeanneau Merry Fisher 795',
        image: '/images/bavaria46cruiser.jpg',
        length: '7.45 m',
        capacity: 6,
        price: '300 €',
    },
    {
        name: 'Bavaria 37 Cruiser',
        image: '/images/sailBoat.jpeg',
        length: '11.30 m',
        capacity: 8,
        price: '400 €',
    },
    {
        name: 'Sunseeker Predator 55',
        image: '/images/predator55.jpg',
        length: '16.76 m',
        capacity: 12,
        price: '1200 €',
    },
    {
        name: 'Dufour 382 Grand Large',
        image: '/images/dufour382.jpg',
        length: '11.23 m',
        capacity: 8,
        price: '500 €',
    },
    {
        name: 'Lagoon 450 F',
        image: '/images/lagoon450f.jpg',
        length: '13.96 m',
        capacity: 12,
        price: '950 €',
    },
    {
        name: 'Jeanneau Sun Odyssey 440',
        image: '/images/sunodyssey440.jpg',
        length: '13.39 m',
        capacity: 10,
        price: '700 €',
    },
    {
        name: 'Bénéteau Oceanis 41.1',
        image: '/images/oceanis41.1.jpg',
        length: '12.43 m',
        capacity: 10,
        price: '600 €',
    },
    {
        name: 'Fountaine Pajot Helia 44',
        image: '/images/helia44.jpg',
        length: '13.30 m',
        capacity: 10,
        price: '1100 €',
    }, 
    // en jpeg
    {
        name: 'Bavaria 46 Cruiser',
        image: '/images/bavaria46cruiser.jpg',
        length: '14.27 m',
        capacity: 10,
        price: '800 €',
    },
    {
        name: 'Jeanneau Sun Odyssey 519',
        image: '/images/sunodyssey519.jpg',
        length: '15.75 m',
        capacity: 12,
        price: '900 €',
    },
    {
        name: 'Lagoon 42',
        image: '/images/lagoon42.jpg',
        length: '12.80 m',
        capacity: 10,
        price: '950 €',
    },
    {
        name: 'Dufour 460 Grand Large',
        image: '/images/dufour460.jpg',
        length: '14.15 m',
        capacity: 10,
        price: '850 €',
    },
    {
        name: 'Bénéteau Oceanis 45',
        image: '/images/oceanis45.jpg',
        length: '13.72 m',
        capacity: 10,
        price: '800 €',
    },
    {
        name: 'Fountaine Pajot Saona 47',
        image: '/images/saona47.jpg',
        length: '14.33 m',
        capacity: 12,
        price: '1200 €',
    },
    {
        name: 'Catamaran Lagoon 400 S2',
        image: '/images/lagoon400s2.jpg',
        length: '11.97 m',
        capacity: 10,
        price: '900 €',
    },
    {
        name: 'Jeanneau Merry Fisher 895',
        image: '/images/merryfisher895.jpg',
        length: '8.95 m',
        capacity: 8,
        price: '500 €',
    },
    {
        name: 'Bavaria 37 Cruiser',
        image: '/images/bavaria37cruiser.jpg',
        length: '11.30 m',
        capacity: 8,
        price: '400 €',
    },
    {
        name: 'Sun Odyssey 410',
        image: '/images/sunodyssey410.jpg',
        length: '12.35 m',
        capacity: 10,
        price: '600 €',
    },
    {
        name: 'Lagoon 42',
        image: '/images/lagoon42.jpg',
        length: '13.10 m',
        capacity: 12,
        price: '750 €',
    },
    {
        name: 'Beneteau Oceanis 38',
        image: '/images/oceanis38.jpg',
        length: '11.50 m',
        capacity: 8,
        price: '510 €',
    },
    {
        name: 'Dufour 530',
        image: '/images/dufour530.jpg',
        length: '16.35 m',
        capacity: 14,
        price: '680 €',
    },
    {
        name: 'Jeanneau Sun Odyssey 349',
        image: '/images/sunodyssey349.jpg',
        length: '10.34 m',
        capacity: 8,
        price: '450 €',
    },
    {
        name: 'Catamaran Lagoon 400',
        image: '/images/lagoon400.jpg',
        length: '11.97 m',
        capacity: 10,
        price: '900 €',
    },
    {
        name: 'Bénéteau First 31.7',
        image: '/images/first31.7.jpg',
        length: '9.60 m',
        capacity: 6,
        price: '350 €',
    },
    {
        name: 'Fountaine Pajot Lucia 40',
        image: '/images/lucia40.jpg',
        length: '11.73 m',
        capacity: 10,
        price: '850 €',
    },
    {
        name: 'Jeanneau Merry Fisher 795',
        image: '/images/merryfisher795.jpg',
        length: '7.45 m',
        capacity: 6,
        price: '300 €',
    },
    {
        name: 'Bavaria 37 Cruiser',
        image: '/images/bavaria37cruiser.jpg',
        length: '11.30 m',
        capacity: 8,
        price: '400 €',
    },
    {
        name: 'Sunseeker Predator 55',
        image: '/images/predator55.jpg',
        length: '16.76 m',
        capacity: 12,
        price: '1200 €',
    },
    {
        name: 'Dufour 382 Grand Large',
        image: '/images/dufour382.jpg',
        length: '11.23 m',
        capacity: 8,
        price: '500 €',
    },
    {
        name: 'Lagoon 450 F',
        image: '/images/lagoon450f.jpg',
        length: '13.96 m',
        capacity: 12,
        price: '950 €',
    },
    {
        name: 'Jeanneau Sun Odyssey 440',
        image: '/images/sunodyssey440.jpg',
        length: '13.39 m',
        capacity: 10,
        price: '700 €',
    },
    {
        name: 'Bénéteau Oceanis 41.1',
        image: '/images/oceanis41.1.jpg',
        length: '12.43 m',
        capacity: 10,
        price: '600 €',
    },
    {
        name: 'Fountaine Pajot Helia 44',
        image: '/images/helia44.jpg',
        length: '13.30 m',
        capacity: 10,
        price: '1100 €',
    },
    {
        name: 'Bavaria 46 Cruiser',
        image: '/images/bavaria46cruiser.jpg',
        length: '14.27 m',
        capacity: 10,
        price: '800 €',
    },
    {
        name: 'Jeanneau Sun Odyssey 519',
        image: '/images/sunodyssey519.jpg',
        length: '15.75 m',
        capacity: 12,
        price: '900 €',
    },
    {
        name: 'Lagoon 42',
        image: '/images/lagoon42.jpg',
        length: '12.80 m',
        capacity: 10,
        price: '950 €',
    },
    {
        name: 'Dufour 460 Grand Large',
        image: '/images/dufour460.jpg',
        length: '14.15 m',
        capacity: 10,
        price: '850 €',
    },
    {
        name: 'Bénéteau Oceanis 45',
        image: '/images/oceanis45.jpg',
        length: '13.72 m',
        capacity: 10,
        price: '800 €',
    },
    {
        name: 'Fountaine Pajot Saona 47',
        image: '/images/saona47.jpg',
        length: '14.33 m',
        capacity: 12,
        price: '1200 €',
    },
    {
        name: 'Catamaran Lagoon 400 S2',
        image: '/images/lagoon400s2.jpg',
        length: '11.97 m',
        capacity: 10,
        price: '900 €',
    },
    {
        name: 'Jeanneau Merry Fisher 895',
        image: '/images/merryfisher895.jpg',
        length: '8.95 m',
        capacity: 8,
        price: '500 €',
    },
    {
        name: 'Bavaria 37 Cruiser',
        image: '/images/bavaria37cruiser.jpg',
        length: '11.30 m',
        capacity: 8,
        price: '400 €',
    },
    {
        name: 'Sun Odyssey 410',
        image: '/images/sunodyssey410.jpg',
        length: '12.35 m',
        capacity: 10,
        price: '600 €',
    },
    {
        name: 'Lagoon 42',
        image: '/images/lagoon42.jpg',
        length: '13.10 m',
        capacity: 12,
        price: '750 €',
    },
    {
        name: 'Beneteau Oceanis 38',
        image: '/images/oceanis38.jpg',
        length: '11.50 m',
        capacity: 8,
        price: '510 €',
    },
    {
        name: 'Dufour 530',
        image: '/images/dufour530.jpg',
        length: '16.35 m',
        capacity: 14,
        price: '680 €',
    },
    {
        name: 'Jeanneau Sun Odyssey 349',
        image: '/images/sunodyssey349.jpg',
        length: '10.34 m',
        capacity: 8,
        price: '450 €',
    },
    {
        name: 'Catamaran Lagoon 400',
        image: '/images/lagoon400.jpg',
        length: '11.97 m',
        capacity: 10,
        price: '900 €',
    },
    {
        name: 'Bénéteau First 31.7',
        image: '/images/first31.7.jpg',
        length: '9.60 m',
        capacity: 6,
        price: '350 €',
    },
    {
      name: 'Fountaine Pajot Lucia 40',
      image: '/images/sailBoat.jpeg',
      length: '11.73 m',
      capacity: 10,
      price: '850 €'
    },
    {
      name: 'Jeanneau Merry Fisher 795',
      image: '/images/sailBoat.jpeg',
      length: '7.45 m',
      capacity: 6,
      price: '300 €'
    },
    {
      name: 'Bavaria 37 Cruiser',
      image: '/images/sailBoat.jpeg',
      length: '11.30 m',
      capacity: 8,
      price: '400 €'
    },
    {
      name: 'Sunseeker Predator 55',
      image: '/images/sailBoat.jpeg',
      length: '16.76 m',
      capacity: 12,
      price: '1200 €'
    },
    {
      name: 'Dufour 382 Grand Large',
      image: '/images/sailBoat.jpeg',
      length: '11.23 m',
      capacity: 8,
      price: '500 €'
    },
    {
      name: 'Lagoon 450 F',
      image: '/images/sailBoat.jpeg',
      length: '13.96 m',
      capacity: 12,
      price: '950 €'
    },
    {
      name: 'Jeanneau Sun Odyssey 440',
      image: '/images/sailBoat.jpeg',
      length: '13.39 m',
      capacity: 10,
      price: '700 €'
    },
    {
      name: 'Bénéteau Oceanis 41.1',
      image: '/images/sailBoat.jpeg',
      length: '12.43 m',
      capacity: 10,
      price: '600 €'
    },
    {
      name: 'Fountaine Pajot Helia 44',
      image: '/images/sailBoat.jpeg',
      length: '13.30 m',
      capacity: 10,
      price: '1100 €'
    }
];

export const getBoats = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(boats);
    }, 1000); // Simulate a network delay
  });
};